title: Hello! I’m Mohamed Nafrees. Welcome to my Data Analytics Projects.
description: Microsoft Certified: Power BI Data Analyst (PL-300) | Microsoft Certified: Fabric Analytics Engineer (DP-600)
theme: jekyll-theme-cayman
